### PR TITLE
Issue#26

### PR DESCRIPTION
**Pull request by HyoukSunKwon**

### CODE REVIEW

**Review by hyunjiLeeTech — COMMENTED** [review]
- I think you accidently push the commits for issue #38 on this pull request. You should create branch when you located at your 'master' branch ('git checkout master' and then git branch [branchName] to create branch). 
- It seems using this branch to work on issue #38 together with issue #26 would be better because you changed DropDownPicker's values on the pull request for issue #38 (pull request #47) ..your choice what branch you want to work on. If you decide to work on this branch, close the pull request #47 you created for issue #38. If you decide to work on pull request #47, you can use that branch.
- Please name the title so we can know what issue you resolved on this pull request when you create pull request (ex Add more vaccine types to the array)

**Comment by ElisaNgLi** [comment]
is this pull request related to #47 ? I think the same work is been done here... We can close #47 and just continue in here the new changes.

**Review by hyunjiLeeTech — CHANGES_REQUESTED** [review]
If you only use this branch to add one more option to gender array, can you work put the code on pull request #47 and close this pull request (#53)? As the master branch has already had other commits and the commits you've pushed to this branch have lots of duplicates (cuz of the issue you created while you created a branch. We discussed before), it becomes tricky to merge this pull request and pull request #47.

**Comment by hyunjiLeeTech** [comment]
Will create another pull request

**Pull request closed without merging**
