### PR TITLE
Fix issue #15 added scaling to DBO fields

### PR DESCRIPTION
**Pull request by ElisaNgLi**
#15 
I kinda found a way to do this using scaling refers to the changes I made for DBO on the GetUserInfoScreen
But, the method I used (scaling) we can implement that method in all of the stylings so it won't affect if the phone screen size changes 

I am going to attach a screenshot between the two phones I am testing 

Left Phone screen size: 4.65"
Right Phone screen size: 5.2"

Screen Shot 2021-03-17 at 8 49 28 PM

The reference I use to find a way to fix the issue: https://medium.com/soluto-engineering/size-matters-5aeeb462900a

### CODE REVIEW

**Review by hyunjiLeeTech — DISMISSED** [review]
It totally works! I'm going to create another issue to adjust fields' width&height size following what you use.

**Comment by hyunjiLeeTech** [comment]
> It totally works! I'm going to create another issue to adjust fields' width&height size following what you use.

When I was about to create another issue for scaling I got we can keep using this pull request...I've found the same issue happens on AddHistoryScreen and EditProfileScreen (DOB field on both screen). Can you please rescale those DOB fields as well? 

- Rescale DOB field on AddHistoryScreen
- Rescale DOB field on EditProfileScreen (DOB and Gender field on EditProfileScreen...it seems quite narrow to put DropDownPicker and Text field in the same line...don't know how you guys think about this @HyoukSunKwon @ElisaNgLi )

image

**Review by hyunjiLeeTech — COMMENTED** [review]
> It totally works! I'm going to create another issue to adjust fields' width&height size following what you use.

When I was about to create another issue for scaling I got we can keep using this pull request...I've found the same issue happens on AddHistoryScreen and EditProfileScreen (DOB field on both screen). Can you please rescale those DOB fields as well? 

- Rescale DOB field on AddHistoryScreen
- Rescale DOB field on EditProfileScreen (DOB and Gender field on EditProfileScreen...it seems quite narrow to put DropDownPicker and Text field in the same line...don't know how you guys think about this @HyoukSunKwon @ElisaNgLi )

image

**Comment by ElisaNgLi** [comment]
Ok, I will rescale the DOB on those two screens... I just push this one first so you can see and maybe add another issue to use the scaling for every part of the style so we don't encounter this issue in the future. 

I think it will be good to use the scaling feature for everything as well not just for the DOB part... we can discuss more of this when we have our meeting

**Comment by hyunjiLeeTech** [comment]
Okay. Let's discuss this on tmr meeting.

**Review by HyoukSunKwon — APPROVED** [review]

**Review by hyunjiLeeTech — APPROVED** [review]

**Pull request merged**
